### ISSUE TITLE
Ruby packaging functionality

### ISSUE THREAD

**Issue by ronaldtse** [tamatebako/tebako#13]
This corresponds to items 2 and 3 here https://github.com/tamatebako/tebako/issues/1#issuecomment-902687931.

This is the first of potentially multiple "packagers", which extracts out a program as a single image to be run on Tebako.

There are several names we can consider for this "packager" activity:
1. imager (person who makes a image, which implies read-only and reflects what this role does)
2. presser (something like distillation, extracts the essence (only the program) into the Tebako image)

Considered these but in favour: "distiller" (already used by Adobe Acrobat), "packer" (used by ruby-packer), "packager" (sounds too generic), "cloner" (sounds a bit simplistic).

So this is the "Ruby imager" or "Ruby presser".

**Comment by ronaldtse** [comment]
We may want to maintain such programming language specific packaging code in separate repos, such as tebako-imager-ruby / tebako-presser-ruby.

**Comment by ronaldtse** [comment]
The user should be able to run something like this:

```sh
$ tebako press ruby entrypoint.rb
=> Image built at entrypoint.rb.dwarfs
```

**Comment by maxirmx** [comment]
@ronaldtse 
Could you please have a look at CLI section here: https://github.com/tamatebako/tebako/edit/master/doc/DEV-NOTES.md ?
Am I moving in a right direсtion  ?

**Comment by ronaldtse** [comment]
@maxirmx can you also have a look at https://github.com/larsch/ocra ? It is just like ruby-packer on Windows, but does not need to re-compile Ruby.

**Comment by maxirmx** [comment]
> @maxirmx can you also have a look at https://github.com/larsch/ocra ? It is just like ruby-packer on Windows, but does not need to re-compile Ruby.

_**ocra does the following**_
_Packaging:_
_Creates an archieve that contains_ 
   - ruby program to be packaged
   - all dependencies
   - ruby interpreter with required dynamic modules

_Complies and links small stub program that includes the archieve described above as a custom data section_ 

_Execution:_
 Runs the stub which extract archieve to temporary folder and calls ruby interpreter with appropriate parameters to execute packaged application
 
Very simple and effective. No need to patch and build ruby.

**Comment by ronaldtse** [comment]
So the only differences are:
- Orca requires extracting the ruby interpreter and code into a temporary folder
- i.e. does not require a file system redirection

Do note that packed-mn using Orca is failing right now due to a dependency that is used by Fontist:
- https://github.com/metanorma/packed-mn/issues/118

I wonder if we could implement an FS redirect layer without patching Ruby but “wrapping” it. Because we don’t want to extract the dependencies.

**Comment by ronaldtse** [comment]
@maxirmx we have previously created [`retrace`](https://github.com/riboseinc/retrace) which allows interception of file system calls of unpatched executables. The same approach would work here.

**Comment by maxirmx** [comment]
I think now I understand the confusion in this discussion and in #1

Ocra packager loads the Ruby program to be packaged and builds the list of loaded dependencies, both native DLLs and ruby gems, then adds Ruby interpreter itseld to the package.
Ruby-packer does not load anything. It creates clean Ruby installation and the runs _gem install_, _bundle deploy_ or something similar and the packages the whole Ruby floder tree with everything installed there.  

Ocra approach implies packager written in Ruby.
Ruby-packer approach can be implemented in any language or with any applicable tool.
