### ISSUE TITLE
No such file 'utf8.h' on `tebako press`

### ISSUE THREAD

**Issue by jgresham** [tamatebako/tebako#135]
```
[ 96%] Building CXX object CMakeFiles/dwarfs.dir/src/dwarfs/util.cpp.o
/root/.tebako/deps/src/_dwarfs_wr/deps/src/_dwarfs/src/dwarfs/util.cpp:30:10: fatal error: utf8.h: No such file or directory
   30 | #include <utf8.h>
      |          ^~~~~~~~
compilation terminated.
```
ubuntu 20.04, arm64, ruby v3.1.4, gcc v10.5.0, clang/++ v12.0.0-3

I'm relatively new to cmake & ruby. I'm trying to create a binary executable of the gem `fpm`

command `tebako press --root='./fpm' --entry=lib/fpm/command.rb --output=fpm-arm64-exe -R 3.1.4`

**Comment by ronaldtse** [comment]
Thanks for the report @jgresham !

@maxirmx can you please help? Perhaps we can also update or provide additional information in the README too.

**Comment by maxirmx** [comment]
@jgresham 
The information in the README was outdated. Sorry for that and thank you for noticing. 

I believe you are missing a package - ```libutfcpp-dev``` but you may find useful to check all items in the updated list here:
https://github.com/tamatebako/tebako/blob/maxirmx-readme-update/README.adoc

**Comment by jgresham** [comment]
> @jgresham The information in the README was outdated. Sorry for that and thank you for noticing.
> 
> I believe you are missing a package - `libutfcpp-dev` but you may find useful to check all items in the updated list here: https://github.com/tamatebako/tebako/blob/maxirmx-readme-update/README.adoc

Thanks! That worked.

Now it looks like I might be misinterpreting `--entry`. Is this the entry `.rb` file of the project? I'm looking to compile [fpm](https://github.com/jordansissel/fpm) and `lib/fpm/command.rb` is stated as the entry point to the gem (https://github.com/jordansissel/fpm/blob/847ded9eba0d707c61c942f6153178de357740b7/lib/fpm/command.rb#L22). Any quick idea of what the issue might be?

```
/root/.tebako/output/source_filesystem/bin/fpm
Successfully installed fpm-1.15.1
1 gem installed
Entry point /root/.tebako/output/source_filesystem/bin/lib/fpm/command.rb does not exist
gmake[3]: *** [CMakeFiles/source_filesystem.dir/build.make:76: CMakeFiles/source_filesystem] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:228: CMakeFiles/source_filesystem.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:342: CMakeFiles/tebako.dir/rule] Error 2
gmake: *** [Makefile:241: tebako] Error 2
Tebako script failed: 'tebako press' build step failed [104]
```

**Comment by maxirmx** [comment]
It is an 'executable packager'.  It cannot package gem as "a library", it can deal with "a program" only. 
You can use ```fpm``` as an entry point and tebako will find it at 'bin/fpm'. 

You may refer to the script that packages similar gem: https://github.com/fontist/fontist/blob/main/.github/workflows/tebako-pack.yml

Also there is a test script(shell) that runs all supported packaging scenarious
https://github.com/tamatebako/tebako/blob/main/tests/scripts/functional-tests.sh

**Comment by maxirmx** [comment]
Well, now I see that examples are missing ....

**Comment by jgresham** [comment]
> It is an 'executable packager'. It cannot package gem as "a library", it can deal with "a program" only. You can use `fpm` as an entry point and tebako will find it at 'bin/fpm'.
> 
> You may refer to the script that packages similar gem: https://github.com/fontist/fontist/blob/main/.github/workflows/tebako-pack.yml
> 
> Also there is a test script(shell) that runs all supported packaging scenarious https://github.com/tamatebako/tebako/blob/main/tests/scripts/functional-tests.sh

Ok, I think I have what its needed for `electron-builder`, that is an fpm binary executable for arm64...

```
root@0deeb46a2e0c:/fpm-arm-binary# fpm -s npm -t deb express
bash: fpm: command not found
root@0deeb46a2e0c:/fpm-arm-binary# ./fpm-arm64-binary -s npm -t deb express
Created package {:path=>"node-express_4.18.3_arm64.deb"}
root@0deeb46a2e0c:/fpm-arm-binary# ./fpm-arm64-binary -v
1.15.1
```
