### ISSUE TITLE
Tebako reads its version from wrong git repository

### ISSUE THREAD

**Issue by d4rky-pl** [tamatebako/tebako#171]
This is most likely a low priority issue as from what I've gathered it only affects the output when running `tebako setup` and `tebako press` and does not affect the build process itself (I may be wrong on that).

When running the `cmake` part of the setup, I've noticed that the version displayed there seemed to make no sense:

```
Setting up tebako packaging environment
-- Found version.txt with 0.7.3
-- Found Git: /opt/homebrew/bin/git (found version "2.42.1")
-- Found annotated tag v0.8.1-305-g0586b37
CMake Warning at tools/cmake-scripts/version.cmake:122 (message):
  Tagged version 0.8.1 doesn't match one from the version.txt: 0.7.3
Call Stack (most recent call first):
  CMakeLists.txt:37 (determine_version)


-- TEBAKO_VERSION: 0.8.1
-- TEBAKO_VERSION_NCOMMITS: 305
-- TEBAKO_VERSION_GIT_REV: 0586b37
-- TEBAKO_VERSION_IS_DIRTY: FALSE
-- TEBAKO_VERSION_COMMIT_TIMESTAMP: 0
-- TEBAKO_VERSION_SUFFIX: +git20240721.305.0586b37
-- TEBAKO_VERSION_FULL: 0.8.1+git20240721.305.0586b37
```

After further investigation I've realized that the reason for that is because the version is actually fetched not from the project but rather from my [asdf](https://asdf-vm.com) installation:

```sh
$ pwd
/Users/matyas/.asdf
$ git describe
v0.8.1-305-g0586b37
```

This in turn comes from the fact `source_dir` passed to cmake is `/Users/matyas/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/tebako-0.7.3`. The entire `.asdf` directory is a git repository (due to how their updating scheme works) and it seems to be confusing the version autodetection.

**Comment by maxirmx** [comment]
Thank you for reporting , @d4rky-pl 
This is a legacy that needs to be cleaned. We used to use this version as a cache key but not anymore.
