### ISSUE TITLE
Develop tests for custom ruby with custom file operations 

### ISSUE THREAD

**Issue by maxirmx** [tamatebako/tebako#19]
(Test cases for #18 )

**Comment by ronaldtse** [comment]
Agree. This is to test whether the packaged ruby can access the memfs and perform operations as expected. 

We probably should also utilize the official ruby specs to test the packaged interpreter.

**Comment by maxirmx** [comment]
> We probably should also utilize the official ruby specs to test the packaged interpreter.

I will try do adopt unit tests which are a part of ruby source package

**Comment by ronaldtse** [comment]
> I will try do adopt unit tests which are a part of ruby source package

We can just run all the ruby source tests on the packaged ruby, right?
