### ISSUE TITLE
Support for Redhat Linux / Rocky Linux

### ISSUE THREAD

**Issue by laurent-martin** [tamatebako/tebako#190]
Anyone has successfully used `tebako` on Rocky Linux 9 ?

I tried on Rocky 9, and got:

```console
$ tebako press --root=$PWD --entry-point=ascli --output=/mnt/w/ascli.exe --Ruby=3.2.4
...
[ 70%] Completed '_zstd'
[ 70%] Built target _zstd
gmake[4]: *** [Makefile:136: all] Error 2
gmake[3]: *** [CMakeFiles/_dwarfs_wr.dir/build.make:86: /home/laurent/.tebako/deps/src/_dwarfs_wr-stamp/_dwarfs_wr-build] Error 2
gmake[2]: *** [CMakeFiles/Makefile2:91: CMakeFiles/_dwarfs_wr.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:257: CMakeFiles/tebako.dir/rule] Error 2
gmake: *** [Makefile:202: tebako] Error 2
Tebako script failed: 'tebako press' build step failed [104]
```

I tried the container:

```
docker run -it --rm -v $PWD:/mnt/w ghcr.io/tamatebako/tebako-ubuntu-20.04:latest tebako press --root=/mnt/w --entry-point=ascli --output=/mnt/w/ascli.exe --Ruby=3.2.4
```

But it does not run:

```console
$ ./ascli.exe
./ascli.exe: /lib64/libpthread.so.0: version `GLIBC_PRIVATE' not found (required by ./ascli.exe)
```

**Comment by ronaldtse** [comment]
@laurent-martin thanks for the report. No I don't think we've tried Tebako on RHEL or Rocky Linux but it's something we can investigate.

@maxirmx could you please help? I believe at RNP we have CentOS/RHEL GHA builds so we can adopt those workflows over here as well.

**Comment by maxirmx** [comment]
There are two different topics here
- an option to run tebako on RedHat or similar systems  (the first failure @laurent-martin mentioned)
- GLIB forward compatibility (the second failure) also here https://github.com/tamatebako/tebako/issues/98 and here https://github.com/metanorma/packed-mn/issues/194

These issues are "orthogonal". 
Making Rhel port is possible but it means doing it all the way through - folly with our patches, dwarfs, tebako
I would rather make tebako port to Ubuntu 24, provide container for packaging and the output shall work for Rocky Linux 9. Theoretically ...

@laurent-martin, will it work for you ?

**Comment by d4rky-pl** [comment]
@maxirmx I found an interesting alternative to what you proposed but it's probably not a viable solution for everyone - I used [a modified version of patchelf](https://github.com/NixOS/patchelf/pull/564) and ran:

```
patchelf --remove-needed-version libc.so.6 GLIBC_PRIVATE ht-x86_64-linux
patchelf --remove-needed-version libpthread.so.0 GLIBC_PRIVATE ht-x86_64-linux
```

So far the binary seems to work on Ubuntu 22 but I didn't stress test it. It could be an option to make things more portable but you're the expert here, feel free to scream at me that this is a horrible hack 😄

**Comment by maxirmx** [comment]
> @maxirmx I found an interesting alternative to what you proposed but it's probably not a viable solution for everyone - I used [a modified version of patchelf](https://github.com/NixOS/patchelf/pull/564) and ran:
> 
> ```
> patchelf --remove-needed-version libc.so.6 GLIBC_PRIVATE ht-x86_64-linux
> patchelf --remove-needed-version libpthread.so.0 GLIBC_PRIVATE ht-x86_64-linux
> ```
> 
> So far the binary seems to work on Ubuntu 22 but I didn't stress test it. It could be an option to make things more portable but you're the expert here, feel free to scream at me that this is a horrible hack 😄

I think this is a good idea :)

**Comment by ronaldtse** [comment]
Will this be an option?

**Comment by maxirmx** [comment]
> Will this be an option?

I think this is a postprocessing option that will make  tebako package built with "older" glibc (pre 3.24) to work on newer gnu-linux versions.

For example, make package built on Ubuntu 20  work on Ubuntu 22/24  (or  Rocky Linux 9)

I will test it

**Comment by maxirmx** [comment]
@laurent-martin  
The latest Ubuntu container https://github.com/tamatebako/tebako-ci-containers/pkgs/container/tebako-ubuntu-20.04 shall produce correct package that wiill work on Rocky Linux

There are some examples here:
https://github.com/tamatebako/tebako-samples/tree/maxirmx-rocky-linux

**Comment by laurent-martin** [comment]
Thanks a lot.
I have tested 0.8.6, and now the generated executable works on Rocky 9.
