### ISSUE TITLE
Metanoma  MacOS | dyld[20061]: Library not loaded: /opt/homebrew/opt/boost/lib/libboost_chrono-mt.dylib

### ISSUE THREAD

**Issue by CAMOBAP** [tamatebako/tebako#222]
- am64: https://github.com/metanorma/packed-mn/actions/runs/12484338315/job/34841618243#step:5:159
 - intel: https://github.com/metanorma/packed-mn/actions/runs/12484338311/job/34841633600#step:5:158

**Comment by maxirmx** [comment]
There was some issue related to homebrew upgrade on GHA runners last week.
Cache created by the old version did not work for the new version.
I had to clear caches manually, no it workd.
