### ISSUE TITLE
Command-line interface for tebako

### ISSUE THREAD

**Issue by ronaldtse** [tamatebako/tebako#24]
Given that we need to use libdwarfs, would it be most suitable to use C++ in Tebako CLI?

**Comment by ronaldtse** [comment]
From @maxirmx :

> There will be two types of executable:
> 1) packager
> 2) packaged program
> 
> I assumed that the packager will use mkdwarfs executable to create filesystem binary file.
> 
> Packaged program will be patched ruby interpreter that will link to libdwarfs and include filesystem binary file as a data section. (It is an option 1 - 'like ruby packer').  
> 
> Option 2 is to build packaged program that is simple start logic only, links to libdwarfs and includes binary file as a data section and put original(unpatched) ruby interpreter inside packaged filesystem.
> 
> In both cases packaged program is C/C++, but the packager can be anything

**Comment by ronaldtse** [comment]
For some reason I got stuck on libdwarfs. We technically could rely on mkdwarfs -- the only concern is its availability on various platforms. There is some convenience derived (in packaging and distribution) to have a single contained binary/solution.

**Comment by ronaldtse** [comment]
From @maxirmx 

> Availability on various platform is an issue anyway.  dwarfs does not have Windows build and I am not sure about MacOS. It means that porting is required and one extra executable does not add too much effort. 
> 
> I believe the real tradeoff is different.  
> 
> If you look at ruby-packer it does not maintain dependencies. Each time you package it rebuilds everything from scratch.  That's because it self contained and the authors cannot implement complex build logic. 
> 
> If we use CMake, it does build process optimization. So repackaging is much faster comparing to ruby-packer. 
> 
> So, the choice is between implementing simple but self contained build logic  versus integration of third party tool
> 
> The same tradeof applies to creation of dwarfs. We can re-implement mkdwarfs or we can use executable that has been created already 
> 
> Please note also that the scope of tebako is really big already.

**Comment by ronaldtse** [comment]
So this is my logic:

1. We need to use `libdwarfs` in tebako so that the created binaries can load DwarFS images. This means that libdwarfs needs to support all platforms we need, macOS, Windows and Linux.
2. `mkdwarfs` is a command provided by DwarFS. It is not available now on macOS and Windows. To make its functionality available to these platforms, we have to port with these options. The consideration here is really to do the minimal work without needing the user to type commands outside of tebako.
  * update mkdwarfs and upstream
  * refactor mkdwarfs to use the platform-independent libdwarfs (but we don't know if libdwarfs will support everything mkdwarfs does) and upstream
  * re-create parts of mkdwarfs functionality in tebako
3. Separate installs of mkdwarfs and tebako can lead to compatibility issues, such as version incompatibility of mkdwarfs (used to create image) vs libdwarfs (in the compiled binary).
4. We do not want the user to manually run mkdwarfs due to usability concerns. For example, for Docker users, they would prefer entering `docker volume cp` rather than `tar -xvf {docker-volume-file}; cp xxx`.

**Comment by maxirmx** [comment]
Closed with #26
