### ISSUE TITLE
Support generation of Windows executables (code-signed)

### ISSUE THREAD

**Issue by ronaldtse** [tamatebako/tebako#27]
Tebako now supports Linux + macOS, we just need to add Windows support.

e.g. https://github.com/codebykevin/ocra/commit/9f9836d35c8aa371083520600a0fc2b22c39572f

**Comment by maxirmx** [comment]
- [ ] dwarfs port (read-only)
- [ ] libdwarfs port
- [ ] tebako pre-release / determine additional functions to be implemented to support Ruby Windows build
- [ ] libdwarfs / implement addtional functions
- [ ] tebako release

**Comment by maxirmx** [comment]
I was able package tebako memfs into Ruby and resolve all issues related to filesystem access.
However, it looks like an option to link MinGW version of Ruby statically is broken in all recent versions (2.7, 3.0, 3.1, 3.2)

I made an experiment with original Ruby (without any tebako patches) as follows:

1.	I use the code from https://github.com/ruby/ruby/tree/ruby_3_1 and GHA workflow at https://github.com/ruby/ruby/blob/ruby_3_1/.github/workflows/mingw.yml as a baseline

2.	I alter configure command in the workflow from 
```
- name: configure
  run: >
    ../src/configure --disable-install-doc --prefix=/.
    --build=$CHOST --host=$CHOST --target=$CHOST
```
       to
``` 
- name: configure
  run: >
     ../src/configure --disable-install-doc --with-static-linked-ext --disable-shared --without-gmp -- prefix=/.
      --build=$CHOST --host=$CHOST --target=$CHOST
```
and uncomment ```option nodynamic``` in ```ext/Setup```

3. The first failure I observe is:
```
C:\msys64\ucrt64\bin\dllwrap.exe: WARNING: C:\msys64\ucrt64\bin\dllwrap.exe is deprecated, use gcc -shared or ld -shared instead
C:\msys64\ucrt64\bin\dllwrap.exe: no export definition file provided.
Creating one, but that may not be what you want
x86_64-w64-mingw32-cc: error: unrecognized command-line option '-mno-cygwin'; did you mean '-mno-clwb'?
C:\msys64\ucrt64\bin\dllwrap.exe: x86_64-w64-mingw32-cc exited with status 1
make: *** [GNUmakefile:73: ruby.exp] Error 1
```
     In order to resolve it I comment out ``` DLLWRAP += -mno-cygwin``` in ```cygwin/GNUmakefile.in```

4. Then I get the second failure:
```
creating ruby.exp
C:\msys64\ucrt64\bin\dllwrap.exe: WARNING: C:\msys64\ucrt64\bin\dllwrap.exe is deprecated, use gcc -shared or ld -shared instead

C:\msys64\ucrt64\bin\dllwrap.exe: no export definition file provided.
Creating one, but that may not be what you want
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: warning: cannot find entry symbol _DllMainCRTStartup@12; defaulting to 0000000063981000
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: warning: cannot find entry symbol _DllMainCRTStartup@12; defaulting to 0000000063981000
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: warning: cannot find entry symbol _DllMainCRTStartup@12; defaulting to 0000000063981000
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ruby.o:ruby.c:(.text+0x54f5): undefined reference to `Init_enc'
collect2.exe: error: ld returned 1 exit status
make: *** [GNUmakefile:74: ruby.exp] Error 1
```
I believe that when ```GNUMakefile``` is generated ```disable-shared``` flag is ignored silently

**Comment by maxirmx** [comment]
https://bugs.ruby-lang.org/issues/19044

**Comment by ronaldtse** [comment]
Thanks @maxirmx ! I'm not sure if Ruby static build on MinGW is officially supported but hope we get a reply. We might consider contributing that portion if necessary.

**Comment by maxirmx** [comment]
@ronaldtse 
UPD
There was no reply from Ruby team regarding staic build on MinGW
I think we need to implement it ourselves if want to continue with an options to contribute it to the mainline.
My preliminate estimate is 2-3 weeks to implement it in a private branch.
If we want to contribute it we will need to support Ruby 3.x while tebako uses Ruby 2.x.  It may require some extra effort. Probably another 2-3 weeks.

**Comment by ronaldtse** [comment]
Thanks @maxirmx . We do have to upgrade Tebako to work with Ruby 3 anyway, so it is unavoidable. Let’s do this first. We should allow building different Ruby versions. 

For the MinGW static build, we should proceed as well, with the goal to contribute back to Ruby mainline.
