### ISSUE TITLE
dbm extension build fails with custom Ruby build

### ISSUE THREAD

**Issue by maxirmx** [tamatebako/tebako#33]
_*** Following extensions are not compiled:
dbm:
	Could not be configured. It will not be installed.
	Check ext/dbm/mkmf.log for more details.

[mkmf.log](https://github.com/tamatebako/tebako/files/7572495/mkmf.log)

It looks like this is a problem inherited from ruby-packer. 
Not sure if it causes/will cause some real problems or can be ignored.  Anyway if ignored, the extension shall be excluded by ext/Setup  patch

**Comment by ronaldtse** [comment]
The `dbm` gem should not be necessary for Metanorma but others may require it.

**Comment by ronaldtse** [comment]
We also had to patch this gem in our `ruby-packer`:
https://github.com/metanorma/ruby-packer/tree/master/.patches/gdbm
