### ISSUE TITLE
Bundler reference in README

### ISSUE THREAD

**Issue by maxirmx** [tamatebako/tebako#58]
Tebako employes the following packaging procedure

1. Pristine environment is created  (referenced as 'tebako environment' further) . Tecnically it is empty directory with GEM_HOME and GEM_PATH unset.
2. Ruby is installed to tebako environment.   PATH is set to point to newly installed Ruby bin directory.
3. Appplication root directory is recursively copied to tebako environment
4. Ruby packaging specification is executed  as described here: https://github.com/tamatebako/tebako#ruby-packaging-specification 
5. Ruby binaries are deleted from tebako environment
6.  mkdwarfs is executed for tebako_environment. Resulting binary is tebako package.

So there is no requirement to install bundler as said here: https://github.com/tamatebako/tebako#supporting-rubygems . Tebako will install it if required.

ronn is dwarfs prerequisite for now. It is used to generate man pages. I think I will create lite version of dwarfs CMake script that on't create man pages and other items that we do not need.  

@ronaldtse  please advise how much of this information we would like to put to readme

**Comment by ronaldtse** [comment]
> please advise how much of this information we would like to put to readme

@maxirmx all please? 😜 Diagrams are even more welcome. We want to make this explanation as clear as possible.

**Comment by maxirmx** [comment]
Closed by the document in https://github.com/tamatebako/tebako.org/issues/5
