### ISSUE TITLE
Building for macOS and Ubuntu arm64

### ISSUE THREAD

**Issue by ronaldtse** [tamatebako/tebako#63]
There are now two target macOS architectures (arm64 vs x86), so we want to:
1. Target building both on GHA
2. Offer the arm64 executable as an uploaded job artifact, so that you can also test the GHA-compiled arm64 one locally

**Comment by ronaldtse** [comment]
From @maxirmx :

I have 11.00 x86 version working.  
I think I will do 10.15 today. It is a matter of selecting XCode version and SDK on GHA runner.  It is there but I cannot figure how to switch to it.

As for arm version there is no arm runner on GHA
It means that in order to support it we need to build x86 dwarfs tools, after that cross-build arm version of "everything" and after that use x86 tools to package arm version.

It does not look too complex unless two caveats:

1. I have some doubts about INCBIN capability to support cross-compilation. So it has to be tested
2. The CI procedure that I described above won't provide for an option to test the output or any intermmediate steps.  It will be very hard to debug.

I have the package running locally on arm, so it is purely CI issue.  

If I have to build a workflow as described (build and package arm version on x86 GHA runner) I think it will take a week.

**Comment by ronaldtse** [comment]
> I think I will do 10.15 today. It is a matter of selecting XCode version and SDK on GHA runner. It is there but I cannot figure how to switch to it.

Available SDK versions on 10.15:
- https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#installed-sdks

GH action to select version:
- https://github.com/marketplace/actions/setup-xcode-version

> 2. The CI procedure that I described above won't provide for an option to test the output or any intermmediate steps. It will be very hard to debug.

Testing macOS with arm64 won't work on GHA, so we can download it and test...

**Comment by maxirmx** [comment]
Let it be arm64 architecture and #54 - x86_64 architecture

**Comment by maxirmx** [comment]
It looks like this type of cross-compilation is not supprted by homebrew in a sense that there is no way to install arm64 libraries on x86_64 MacOS 11

Practiaclly it means cross-compilation of all libraries  (3-4 hours per build on GHA) or some custom brew formula

Maybe someone is able to help:
https://stackoverflow.com/questions/70821136/can-i-install-arm64-libraries-on-x86-64-with-homebrew

**Comment by ronaldtse** [comment]
@maxirmx wow, you already got your answer! That was fast.

**Comment by maxirmx** [comment]
Dwarfs uses thrift which is essentially a compiler. So build script  (1) builds thrift, then (2) uses it to create filesytem metadata definitions, then  (3) builds a library that processes metadata definition reusing some of the object files created at step (1). In the case of arm64 build on x86_64 steps (1) and (2) need to be x86 while step (3) needs to be arm64

Similar ruby build script (1) builds miniruby (2) uses miniruby to generate some extra files (3) builds full ruby using some of the object files created at step (1)  
In the case of arm64 build on x86_64 steps (1) and (2) need to be x86 while step (3) needs to be arm64

It is possible th create build scripts both for dwarfs and for ruby as described above.  For dwarfs complexity is low, for Ruby complexity is high.  Howeevr we need to accept the fact that our build scripts will diverge from baselines in both cases.

**Comment by maxirmx** [comment]
If I attempt to package something bigger then trivial example I am getting error
```
<jemalloc>: Unsupported system page size
```

Something like: https://github.com/jemalloc/jemalloc/issues/467
The solution is to specify jemalloc low-level parameters during cross-compilation

We have to use jemalloc since otherwise dwarfs runs out of memory when metanorma is packaged
We have to build jemalloc on MacOS since homebrew version does not link statically

**Comment by maxirmx** [comment]
We are facing similar issue
https://github.com/rubygems/rubygems/issues/4269

**Comment by ronaldtse** [comment]
> We have to use jemalloc since otherwise dwarfs runs out of memory when metanorma is packaged
> We have to build jemalloc on MacOS since homebrew version does not link statically

Sound reasonable.

**Comment by ronaldtse** [comment]
> We are facing similar issue
> [rubygems/rubygems#4269](https://github.com/rubygems/rubygems/issues/4269)

Is this in packed-mn or in another implementation? The way to resolve it seems to be to add the platforms to Gemfile.lock.

**Comment by maxirmx** [comment]
When it comes to native extensions the only (partially ?) working approach is to build several versions of ruby and combine cross-compilation environment as described here:
 
https://ruby-talk.ruby-lang.narkive.com/6yJeTNdl/rbconfig-rb-and-destdir-confusion-while-cross-compiling-ruby-gems

**Comment by ronaldtse** [comment]
@maxirmx the issue in ffi gem seems to have been solved:
* https://github.com/ffi/ffi/issues/944#issuecomment-1073265175 points to https://github.com/ffi/ffi/pull/936
* https://github.com/ffi/ffi/pull/936 was closed and is superseded by https://github.com/ffi/ffi/pull/965
* https://github.com/ffi/ffi/pull/965 was closed and is superseded by https://github.com/ffi/ffi/pull/968
* https://github.com/ffi/ffi/pull/968 was merged

Can you revisit this, and close https://github.com/ffi/ffi/issues/944 when appropriate? Thanks.

**Comment by maxirmx** [comment]
@ronaldtse
I think cross-compilation would be too complex anyway.
Cirrus CI say that they have MacOS Ventura arm64 runners.  If you do not mind trying it could you please enable Cirrus CI for this repository, libdwarfs and dwarfs
It now references other organization -- metanorma/tebako; metanorma/dwarfs enabled 

Thank you

**Comment by ronaldtse** [comment]
@maxirmx I have installed CIrrus CI now for this org. Thanks.
