### ISSUE TITLE
Build pre-built tebako packages for multiple platforms

### ISSUE THREAD

**Issue by ronaldtse** [tamatebako/tebako#66]
Like this: https://github.com/abhinavsingh/proxy.py/pull/877

Platforms to support:

```
linux/386
linux/amd64
linux/arm64/v8
linux/aarch64
```

**Comment by ronaldtse** [comment]
We will have to extend this approach to the Tebako patched interpreters too.

**Comment by maxirmx** [comment]
Implemented in https://github.com/tamatebako/tebako-ci-containers
