### ISSUE TITLE
Publish policy on support of Ruby versions

### ISSUE THREAD

**Issue by maxirmx** [tamatebako/tebako#75]
There shall be some policy for Tebako regarding Ruby versions to be supported

If we follow Ruby stable releases (https://www.ruby-lang.org/en/downloads/) today(Feb 15th, 2022) we shall support
2.6.9
2.7.5
3.0.3
3.1.0

_Originally posted by @maxirmx in https://github.com/tamatebako/tebako/issues/45#issuecomment-1040601771_

**Comment by ronaldtse** [comment]
Agree with stable releases. I don't think we need to support 2.6 since it's rather old now.
