### ISSUE TITLE
Tebako package build on Ubuntu 20 is not compatible with Ubuntu 22

### ISSUE THREAD

**Issue by maxirmx** [tamatebako/tebako#98]
Tebako package build on Ubuntu 20 is not compatible with Ubuntu 22  due to glob issues
related to #53 and https://github.com/metanorma/packed-mn/issues/194

**Comment by d4rky-pl** [comment]
Just ran into this issue, any news or workarounds @maxirmx ?

**Comment by maxirmx** [comment]
I will make a port to Ubuntu 24, create container for packaging and the output shall be backward comaptible.
It is a matter of week I guess.

**Comment by maxirmx** [comment]
gem v0.8.6
