### ISSUE TITLE
Create tebako as a Ruby gem

### ISSUE THREAD

**Issue by ronaldtse** [tamatebako/tebako#99]
From https://github.com/tamatebako/tebako/pull/96#issuecomment-1586448139

The goal is to achieve:

```sh
$ gem install tebako
$ tebako press --root=packed-mn --entry-point=bin/metanorma --output=metanorma-package
```

```sh
$ tebako press \
  --root='~/projects/myproject' \
  --entry=start.rb \
  --output=/temp/myproject.tebako
```

**Comment by ronaldtse** [comment]
Things to be done:
* Move `[exe/package](https://github.com/tamatebako/tebako/issues/99#diff-fe73f1795571ca08228e847505cf359a7beef5026c3dfdef75b1582da283b50f)` into `lib/tebako/packager.rb`.
* Move most code from `exe/tebako` into `lib/tebako/cli.rb`

**Comment by maxirmx** [comment]
Will do
Thank you, @ronaldtse
